#!/usr/bin/env bash

DictionarySize="$1"; shift
FileName="$1"; shift
FilesPath=("$@")

Files=""

if [ "$DictionarySize" == "zenity" ]; then
	DictionarySize="$(zenity --list 16m 32m 64m 128m 256m 512m 1024m 2048m --column "Dictionary Size" --text "Larger size = better compression, but requires more RAM.\nDo not use a dictionary larger than 256m unless necessary." --height=400)"
	if [ "$DictionarySize" == "" ]; then exit; fi
	FileNameFull="$FileName""_$DictionarySize.7z"
else
	exit
fi

function _pack_archive() {
	if [ -e "$FileNameFull" ]; then FileNameFull="$FileName""_$DictionarySize_""_$RANDOM"".7z"; fi
	7zzs a -snl -mx9 -m0=LZMA2:d"$DictionarySize" -ms=2g -mqs=on -mmt=3 "$FileNameFull" "${FilesPath[@]}"
}

_pack_archive

echo -e "\n -= Complete =-"

read pause

# MIT License
#
# Copyright (c) 2024 Chimbal
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
