#!/usr/bin/env bash

Mode="$1"; shift
Files=("$@")
ErrorFiles=""

if [ "$Mode" == "benchmark" ]; then
	Param="$(zenity --list Default 1 2 4 6 8 12 16 32 64 --column "Threads" --text "Standard 7-Zip performance test.\n You can select the number of threads to use from the list." --height=400)"
	if [ "$Param" == "" ]; then exit; fi
	if [ "$Param" == "Default" ]; then
		7zzs b
	else
		7zzs b "-mmt$Param"
	fi
	echo -e "\n -= Complete =-"
	read pause
	exit
fi

function _test_archives() {
	echo -e "Testing... \n"
	for i in "${!Files[@]}"; do
		CurrentFile="${Files[$i]}"
		
		# Run prepared command
		if 7zzs t "$CurrentFile"; then echo -e "\n $CurrentFile: Finished.\n\n"
		else ErrorFiles="${ErrorFiles}\n $CurrentFile"; fi
	done
}


function _list() {
	echo -e "Listing... \n"
	for i in "${!Files[@]}"; do
		CurrentFile="${Files[$i]}"
		
		# Run prepared command
		if 7zzs l "$CurrentFile"; then echo -e "\n $CurrentFile: Finished.\n\n"
		else ErrorFiles="${ErrorFiles}\n $CurrentFile"; fi
	done
}

if [ "$Mode" == "test" ]; then _test_archives
elif [ "$Mode" == "list" ]; then _list
fi

echo -e "\n -= Complete =-"
echo -e "$ErrorFiles"

read pause

# MIT License
#
# Copyright (c) 2024 Chimbal
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
